name: Build and Deploy Node.js App to Azure Web App - Group8md

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Start backend
        run: |
          cd backend
          nohup npm start &
          sleep 10
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip backend/*
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACA4683C2B6E4F49BF2B70D4F4E8BF9D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA42B153731F425BAA2E3CB2E46B349D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BBBB964AAA844E50954C96FE152A5DCF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'group8Backend'
          package: ./release.zip